routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

<<<<<<< HEAD
<<<<<<< HEAD
Route::get('candidates/mycandidate','CandidatesController@myCandidate')->name('candidate.mycandidate')->middleware('auth');
Route::get('candidates/shortcandidate','CandidatesController@shortCandidates')->name('candidate.shortcandidate')->middleware('auth');
=======
=======
>>>>>>> parent of ee25568... first coomit
Route::get('candidates/mycandidate','CandidatesController@mycandidate')->name('candidate.mycandidate')->middleware('auth');

>>>>>>> parent of ee25568... first coomit
Route::resource('candidates', 'CandidatesController')->middleware('auth');

Route::get('candidates/changestatus/{cid}/{sid}','CandidatesController@changeStatus')->name('candidate.changestatus')->middleware('auth');
Route::get('candidates/changeuser/{cid}/{uid?}','CandidatesController@changeUser')->name('candidate.changeuser')->middleware('auth');
Route::post('candidates/changestatusinf/','CandidatesController@changeStatusinfo')->name('candidate.changestatusinf')->middleware('auth');
Route::get('candidates/info/{id}','CandidatesController@Info')->name('candidate.info')->middleware('auth');

Route::get('users/add', '\App\Http\Controllers\Auth\RegisterController@showRegistrationForm')->name('users.add')->middleware('auth');
Route::post('users/create', '\App\Http\Controllers\Auth\RegisterController@adduser')->name('users.create')->middleware('auth');
Route::get('users/{id}/delete/', 'UsersController@destroy')->name('user.delete')->middleware('auth');
Route::resource('users', 'UsersController')->middleware('auth');


Route::get('/hello',function(){
return'Hello Larevel';
});

Route::get('/student/{id}',function($id='No student found'){
    return'We got student with id'.$id;
    });

    Route::get('/car/{id?}',function($id=null){
        //TODO VALIDATE FOR INTEGER
        if(isset($id)){
            return"We got car $id"; 

        }else{
            return'we need the id to find your car';

        }
    });

        Route::get('/comment/{id}', function ($id) {
            return view('comment', compact('id'));
        });



        Route::get('/users/{email}/{name?}', function ($email,$name=null) {
                if(isset($name)){    
                }
                else{
                $name='name missing';
                }

                return view('users', compact('email','name'));
                
  
    
    });
    
    
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Candidate.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Candidate extends Model
{
    protected $fillable = [
        'name',
        'email',
        'user_id',
        
        'age',
          
    ];

    public function status_can (){
        return $this->belongsTo('App\Status','status_id');
    }

  

    
    public function owner (){
        return $this->belongsTo('App\User','user_id');
    }
}

app/Http/Controllers/CandidatesController.php
<?php
//http://localhost/recruit/public/candidates
namespace App\Http\Controllers;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Gate;
use Illuminate\Http\Request;
use App\Status;
use Illuminate\Support\Facades\DB;


use App\Candidate;
use App\User;
//full name is "APP\Http\Controllers\CandidatesController";
class CandidatesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    
<<<<<<< HEAD
<<<<<<< HEAD
   # public function mycandidate(Request $request)
  #  {
   #  if(Auth::user()) { 
    #    $id = Auth::id();
   #     $candidates = Candidate::where('user_id',$id)->get();
   #    $users = User::where('id',$id)->get();
   #    $statuses = Status::all();
   #     return view('candidates.index', compact('candidates', 'users', 'statuses'));
  #   } 
  #  }



    public function myCandidate()
=======
    public function mycandidate(Request $request)
>>>>>>> parent of ee25568... first coomit
=======
    public function mycandidate(Request $request)
>>>>>>> parent of ee25568... first coomit
    {
     if(Auth::user()) { 
        $id = Auth::id();
        $candidates = Candidate::where('user_id',$id)->get();
       $users = User::where('id',$id)->get();
       $statuses = Status::all();
        return view('candidates.index', compact('candidates', 'users', 'statuses'));
     } 
<<<<<<< HEAD
    }

 public function shortCandidates()
    {
        $candidates = Candidate::all()->sortBy('age', $options = SORT_REGULAR, $descending = false);
       
        $users = User::all();
        $statuses = Status::all();
        return view('candidates.index', compact('candidates','users','statuses'));
    
=======
>>>>>>> parent of ee25568... first coomit
    }


    
    
     public function index()
    {
  
        $candidates = Candidate::all();
        $users = User::all();
        $statuses = Status::all();
        return view('candidates.index', compact('candidates','users','statuses'));
    
    }

public function changeUser($cid,$uid=null){
    $candidate= Candidate::findOrfail($cid);
    $candidate->user_id=$uid;
    $candidate->save();
    return redirect('candidates');
}

#public function changeStatus($cid,$sid){
   # $candidate= Candidate::findOrfail($cid);
   ## $candidate->status_id=$sid;
  #  $candidate->save();
   # return redirect('candidates');
#}

public function changeStatus($cid, $sid)
{
    $candidate = Candidate::findOrFail($cid);
<<<<<<< HEAD
<<<<<<< HEAD

    if(Gate::allows('change-status', $candidate))
    {
        $from = $candidate->status_can->id;
        if(!Status::allowed($from,$sid)) return redirect('candidates');        
        $candidate->status_id = $sid;

        $candidate->save();
    }else{
        Session::flash('notallowed', 'You are not allowed to change the status of the user becuase you are not the owner of the user');
    }
    return back();
    //return redirect('candidates');
}   




   
=======
=======
>>>>>>> parent of ee25568... first coomit
    $from = $candidate->status_can->id;
    if(!Status::allowed($from,$sid)) return redirect('candidates');        
    $candidate->status_id = $sid;
    $candidate->save();
    return redirect('candidates');
}          
<<<<<<< HEAD
>>>>>>> parent of ee25568... first coomit
=======
>>>>>>> parent of ee25568... first coomit
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('candidates.create');
    }

    
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $candidate = new Candidate();
        $can=$candidate-> create($request->all());
        $can->status_id=1;
       #  $candidate->name = $request->name;
   # $candidate->email = $request->email;
        $can->save();
        return redirect('candidates');
    }

    
    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $candidate = Candidate::findOrFail($id);
        return view('candidates.edit',compact('candidate'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
     

        $candidate = Candidate::findOrFail($id);
           # $candidate-> update($request->except(['_token']));
           $candidate-> update($request->all());
        
        $candidate->save();

        return redirect('candidates');

    }

    public function changeStatusinfo(Request $request){ 
        $cid = $request->id;
        $sid = $request->status_id;
        $candidate = Candidate::findOrFail($cid);
      
        if(Gate::allows('change-status', $candidate))
        {
            $from = $candidate->status_can->id;
            if(!Status::allowed($from,$sid)) return redirect('candidates');        
            $candidate->status_id = $sid;
    
            
            $candidate->save();
        }else{
            Session::flash('notallowed', 'You are not allowed to change the status of the user becuase you are not the owner of the user');
        }
        return redirect('candidates');
      
    }
    
    
    
    
    

    public function Info($id)
    {
        $candidate = Candidate::findOrFail($id);
        
        return view('candidates.info',compact('candidate'));

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */

     
    public function destroy($id){

            $candidate = Candidate::find($id);
            $candidate->delete();
            return redirect('candidates');
        //
    }
}

resources/views/candidates/create.blade.php
@extends('layouts.app')

@section('content')    
@section('title', 'Create candidate')
<div class="row">
    <div class="col-sm-8 offset-sm-2">
        <h1 class="display-3">Create candidate</h1>

        @if ($errors->any())
        <div class="alert alert-info" role="alert">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        <br /> 
        @endif
        
         
                    
                    <form method = "post" action = "{{action('CandidatesController@store')}}">
                    @csrf
                    <div>

                        <label for = "name"> Candidate name </label>
                        <input type = "text" name = "name">
                    </div>   
                    
                    <div>
                        <label for = "email"> Candidate email</label>
                        <input type = "text"  name = "email">
                    </div>
                    <div>
                        <label for = "age">Candidate Age</label>
                        <input type = "number"  name = "age">
                    </div>


                    <div>
                    <button type="submit" class="btn btn-primary">Create candidate</button>
                   
                    </div>

                    </form>
                    @endsection

resources/views/candidates/edit.blade.php
@extends('layouts.app')


@section('content')  
@section('title', 'Edit candidate')
<div class="row">
    <div class="col-sm-8 offset-sm-2">
        <h1 class="display-3">Update a contact</h1>

        @if ($errors->any())
        <div class="alert alert-info" role="alert">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        <br /> 
        @endif 
                    <form method = "post" action = "{{action('CandidatesController@update', $candidate->id)}}">
                    @method('PATCH') 
                    @csrf
                    
                    <div>
                        <label for = "name"> Candidate name </lable>
                        <input type = "text" name = "name" value = {{$candidate->name}} />
                    </div>   
                    
                    <div>
                        <label for = "email"> Candidate email</lable>
                        <input type = "text" name = "email" value = {{$candidate->email}} >
                    </div>
                    <div>
                        <label for = "age"> Candidate age</lable>
                        <input type = "namber" name = "age" value = {{$candidate->age}} >
                    </div>

                    
                     <button type="submit" class="btn btn-primary">Update</button>

    
                     </form>
                    </div>
                    </div>
                   
                    @endsection
 

resources/views/candidates/index.blade.php
@extends('layouts.app')

  
@section('content')  
<<<<<<< HEAD
<<<<<<< HEAD
@section('title', 'Candidates')
@if(Session::has('notallowed'))
<div class = 'alert alert-danger'>
    {{Session::get('notallowed')}}
</div>
@endif

=======
>>>>>>> parent of ee25568... first coomit
=======
>>>>>>> parent of ee25568... first coomit
              
        <h2 class="text-center"> List of candidates</h2>
      </br>  <table class="table table-bordered" style="width
      :70%;" align="center"   border-collapse="cllapse" style="width:70%;">
            <tr>
                <th>id</th><th>Name</th><th>Email</th><th><a class="nav-link" href=" {{ route ('candidate.shortcandidate')}}" > Age</a></th><th>Statuse candidate</th><th>Owner</th><th>Created</th><th>Updated</th> <th>Edit</th><th>Delet</th><th>full info</th>   
            </tr>
            <!-- the table data --> 
            @foreach($candidates as $candidate)
            @if($candidate->status_id == 2 || $candidate->status_id ==4 )
       <tr class="table-danger">
          @elseif($candidate->status_id == 5) 
          <tr class="table-success">  
          @else
          <tr>
          @endif   

                
                    <td>{{ $candidate->id}}</td>
                    <td>{{ $candidate->name}}</td>
                    <td>{{ $candidate->email}}</td>
                    <td>{{ $candidate->age}}</td>
                    <td><div class="dropdown" >
                      @if (null != App\Status::next($candidate->status_id))    
                      <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        @if (isset($candidate->status_id))
                        {{$candidate->status_can->name}}
                        @endif
                      </button>
                      @else 
                      {{$candidate->status_can->name}}
                      @endif
                                   
                      @if(App\Status::next($candidate->status_id) != null )
                      <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                      @foreach(App\Status::next($candidate->status_id) as $status)
                        <a class="dropdown-item" href=" {{ route ('candidate.changestatus',[ $candidate->id,$status->id])}}" ->{{$status->name}}</a>
                       
                    @endforeach
                      </div>
                      @endif

                    <td><div class="dropdown">
  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    @if (isset($candidate->user_id))
    {{$candidate->owner->name}}
    @else()
    Assign owner
    @endif
  </button>
  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
  @foreach($users as $user)
    <a class="dropdown-item" href=" {{ route ('candidate.changeuser',[ $candidate->id,$user->id])}}" ->{{$user->name}}</a>
   
@endforeach
  </div>
</div>
</td>
                    <td>{{ $candidate->created_at}}</td>
                    <td>{{ $candidate->updated_at}}</td>
                    <td>
    <a href="{{ route('candidates.edit',$candidate->id)}}" class="btn btn-primary"> Edit</a>

</td>
<td>
    <form action="{{ route('candidates.destroy', $candidate->id)}}" method="post">
    @csrf
    @method('DELETE')
    <button class="btn btn-danger"  type="submit">Delete</button>
    </form>
</td>
                
                <td>
                  <a href="{{ route('candidate.info',$candidate->id)}}" class="btn btn-primary"> info</a>
              
              </td>
                
            </tr>
        
@endforeach

        </table>       
        </br>

        </div>

        @endsection

resources/views/candidates/info.blade.php
@extends('layouts.app')

  
@section('content')  
@section('title', 'info')
<div class="row">
    <div class="col-sm-8 offset-sm-2">

<h2 class="text-center"> info candidat</h2>

<div>
<label for = "name"> candidate id:</label>
{{ $candidate->id}} 
</div>
<div>
<label for = "id"> candidate name: </label>
{{ $candidate->name}} 
    </div>
<div>
<label for = "email"> candidate email: </label>
{{ $candidate->email}} </div> 
<div>
<label for = "age"> candidate age :
</label>
{{ $candidate->age}} 
</div>
<div>
<label for = "status_id"> candidate status:</label>    {{$candidate->status_can->name}}
</div>
<div >
<label for = "status_id">  change candidate status:</label>
<div class="col-md-6">
    <form method="POST" action="{{ route('candidate.changestatusinf') }}">
        @csrf  
        <div class="form-group row">
        <label for="status_id" class="col-md-4 col-form-label text-md-right"></label>
        <div class="col-md-6">
            @if (null != App\Status::next($candidate->status_id)) 
            <select class="form-control" name="status_id">                                                                         
              @foreach (App\Status::next($candidate->status_id) as $status)
              <option value="{{ $status->id }}"> 
                  {{ $status->name }} 
              </option>
              @endforeach    
            </select>
        </div>
        <input name="id" type="hidden" value = {{$candidate->id}} >
        <div class="form-group row mb-0">
                <div class="col-md-6 offset-md-4">
                    <button type="submit" class="btn btn-primary">
                        Change status
                    </button>
                </div>
                @else   The candidate has reached a final state, cannot be changed
                @endif

        </div>                    
    </form> 
        @endsection